spring.application.name=BEPhim
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://mongo3:27019/webphim?directConnection=true

# External API base
ophim.base-url=https://ophim1.com/v1/api/

# Response compression
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,text/plain,text/html,text/xml,text/css,application/javascript

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
